name: CI-CD 

on: push

jobs:
  Dockerizing-Go:
  runs_on: ubuntu-latest
  steps:
  - name: Checkout
    uses: actions/checkout@v2
  - name: Building Docker Image
    run: | 
        docker build -t gocicd .
  - name: Running Docker Image 
    run: |
        docker run --rm --name testings gocicd

