name: CI-CD 

on: push

jobs:
  Dockerizing-Go:
   name: Testing Docker with Github Actions
   runs-on: ubuntu-latest
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Building Docker Image
      run: | 
          docker build -t gocicd .
    - name: Running Docker Image
      run: |
          docker run --rm --name testings gocicd
    - name: Viewing all docker images 
      run: |
          docker images ls   
    - name: Deleting the docker image
      run: |
          docker rmi -f gocicd
