name: Hello-World

on: push

jobs:
  Check-Go-Version:
    name: Testing github actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        run: echo "Hello CI-CD"
        env:
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

