name: Hello-World

on: push

jobs:
  Check-Go-Version:
    name: Testing github actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting Go 
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Checking Version
        run: go version 
  
  Building-Go-Application:
    name: Building with github actions
    runs-on: ubuntu-latest
    steps:
      - name: Building code
        needs: Check-Go-Version
        if: always()
        run: go build -v .

  Running-Go-Application:
    name: Running with github actions
    runs-on: ubuntu-latest
    steps:
      - name: Running code
        needs: Building-Go-Application
        if: always()
        run: ./golang

        env:
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

