name: Hello-World

on: push

jobs:
  go-run:
    name: Testing github actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setting Go 
        uses: actions/setup-go@v4
      - name: Running Go
        run: go run main.go
        env:
          DEFAULT_BRANCH: main 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

